version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb-container
    restart: always
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - backend

  dotnet-app:
    build:
      context: .  # Katalog, w którym znajduje się Dockerfile (aktualny katalog)
      dockerfile: Dockerfile # Nazwa pliku Dockerfile
    container_name: dotnet-app
    restart: always
    ports:
      - "8080:80" # Zmień port, jeśli twoja aplikacja działa na innym porcie
    environment:
      ConnectionStrings__Default: "Server=mariadb-container;Port=3306;Database=books;User=root;Password=;"
    depends_on:
      - mariadb
    networks:
      - backend

networks:
  backend:

volumes:
  mariadb_data: